[project]
name = "nbdev-hello-world"
version = "0.1.0"
description = "Add a short description here"
channels = ["conda-forge"]
platforms = ["osx-64"]

[tasks]

[dependencies]
jupyterlab = ">=4.2.0,<4.3"
nbdev = ">=2.2.10,<2.3"
